# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Modelblocks documentation
site_url: https://modelblocks.readthedocs.io/
repo_name: docs
repo_url: https://github.com/modelblocks-org/docs/
edit_uri: edit/main/docs/
extra_css:
  - css/extra.css
theme:
  font:
    text: Lato
    code: Fira Code
  name: material
  features:
  - navigation.indexes
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky
  - content.code.copy
  - content.code.annotate
  - content.tooltips
  - search.suggest
  - search.highlight
  - search.share
  - toc.follow
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - toc:
      anchorlink: false
      permalink: "¶"
      toc_depth: 4
plugins:
  - autorefs
  - git-committers:
      enabled: true
      repository: modelblocks-org/docs
      branch: main
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: true
            filters:
              - "!^_"
            heading_level: 1
            show_root_heading: true
            merge_init_into_class: true
            show_if_no_docstring: true
            signature_crossrefs: true
            show_root_toc_entry: false
            show_signature_annotations: true
            inherited_members: false
            show_labels: false
          paths: [src]
          inventories:
            - https://docs.python.org/3/objects.inv
  - enumerate-headings:
        include:
          - developer/convention.md
        start_level: 2
        increment_across_pages: false
        toc_depth: 4
  - search
nav:
  - Home: index.md
  - Using Modelblocks:
    - user/index.md
    - user/setup.md
    - user/background.md
    - user/basics.md
  - Development guidelines:
    - developer/index.md
    - developer/setup.md
    - developer/convention.md
    - developer/best.md

copyright: Copyright &copy; since 2025 <a href="https://github.com/modelblocks-org/docs/blob/main/AUTHORS">Modelblocks contributors</a> (Apache 2.0 licensed)
